=== FabrizioLanzillo/Pipelined-Application-for-Secure-POS-Monitoring-System/secure_pos/data/ingestion_system/config_schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://it.unipi.sse/config_schema.json",
    "type": "object",
    "required": [
        "ip_address",
        "port",
        "database_path",
        "preparation_system_url",
        "monitoring_system_url",
        "min_transactions_per_session",
        "max_invalid_attributes_allowed",
        "execution_window_length",
        "monitoring_window_length",
        "is_development_mode"
    ],
    "properties": {
        "ip_address": {
            "type": "string"
        },
        "port": {
            "type": "integer"
        },
        "database_path": {
            "type": "string"
        },
        "preparation_system_url": {
            "type": "string"
        },
        "monitoring_system_url": {
            "type": "string"
        },
        "min_transactions_per_session": {
            "type": "integer"
        },
        "max_invalid_attributes_allowed": {
            "type": "integer"
        },
        "execution_window_length": {
            "type": "integer"
        },
        "monitoring_window_length": {
            "type": "integer"
        },
        "is_development_mode": {
            "type": "boolean"
        }
    }
}

=== FabrizioLanzillo/Pipelined-Application-for-Secure-POS-Monitoring-System/secure_pos/data/ingestion_system/config.json
{
    "ip_address": "0.0.0.0",
    "port": 8000,
    "database_path": "ingestion_system.db",
    "preparation_system_url": "http://10.0.0.1:8000/",
    "monitoring_system_url": "http://10.0.0.2:8000/",
    "min_transactions_per_session": 5,
    "max_invalid_attributes_allowed": 5,
    "execution_window_length": 5000,
    "monitoring_window_length": 50,
    "is_development_mode": true
}
